### ISSUE TITLE
possible misuse of CAS

### ISSUE THREAD

**Issue by davecheney** [mitghi/buffpool#1]
https://github.com/mitghi/buffpool/blob/master/mempool.go#L130
```
if ok := cas(); ok {
}
```
a. doesn't do anything if cas succeeds _or_ fails
b. you probably wanted a `for` loop; `for !cas() { }`
c. `if ok := someFunc(); ok {` can be rewritten as just `if someFunc() { `

**Comment by mitghi** [comment]
Thank you very much, Mr. Cheney, I very appreciate it. I changed the code as you directed and working on a fix for data races.
